export const Countrydata = [
  {
    value: "Afghanistan",
    label: "Afghanistan",
    dial_code: "+93",
    code: "AF",
  },
  {
    value: "Aland Islands",
    dial_code: "+358",
    code: "AX",
    label: "Aland Islands",
  },
  {
    value: "Albania",
    dial_code: "+355",
    code: "AL",
    label: "Albania",
  },
  {
    value: "Algeria",
    dial_code: "+213",
    code: "DZ",
    label: "Algeria",
  },
  {
    value: "AmericanSamoa",
    dial_code: "+1684",
    code: "AS",
    label: "AmericanSamoa",
  },
  {
    value: "Andorra",
    dial_code: "+376",
    code: "AD",
    label: "Andorra",
  },
  {
    value: "Angola",
    dial_code: "+244",
    code: "AO",
    label: "Angola",
  },
  {
    value: "Anguilla",
    dial_code: "+1264",
    code: "AI",
    label: "Anguilla",
  },
  {
    value: "Antarctica",
    dial_code: "+672",
    code: "AQ",
    label: "Antarctica",
  },
  {
    value: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
    label: "Antigua and Barbuda",
  },
  {
    value: "Argentina",
    dial_code: "+54",
    code: "AR",
    label: "Argentina",
  },
  {
    value: "Armenia",
    dial_code: "+374",
    code: "AM",
    label: "Armenia",
  },
  {
    value: "Aruba",
    dial_code: "+297",
    code: "AW",
    label: "Aruba",
  },
  {
    value: "Australia",
    dial_code: "+61",
    code: "AU",
    label: "Australia",
  },
  {
    value: "Austria",
    dial_code: "+43",
    code: "AT",
    label: "Austria",
  },
  {
    value: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
    label: "Azerbaijan",
  },
  {
    value: "Bahamas",
    dial_code: "+1242",
    code: "BS",
    label: "Bahamas",
  },
  {
    value: "Bahrain",
    dial_code: "+973",
    code: "BH",
    label: "Bahrain",
  },
  {
    value: "Bangladesh",
    dial_code: "+880",
    code: "BD",
    label: "Bangladesh",
  },
  {
    value: "Barbados",
    dial_code: "+1246",
    code: "BB",
    label: "Barbados",
  },
  {
    value: "Belarus",
    dial_code: "+375",
    code: "BY",
    label: "Belarus",
  },
  {
    value: "Belgium",
    dial_code: "+32",
    code: "BE",
    label: "Belgium",
  },
  {
    value: "Belize",
    dial_code: "+501",
    code: "BZ",
    label: "Belize",
  },
  {
    value: "Benin",
    dial_code: "+229",
    code: "BJ",
    label: "Benin",
  },
  {
    value: "Bermuda",
    dial_code: "+1441",
    code: "BM",
    label: "Bermuda",
  },
  {
    value: "Bhutan",
    dial_code: "+975",
    code: "BT",
    label: "Bhutan",
  },
  {
    value: "Bolivia",
    dial_code: "+591",
    code: "BO",
    label: "Bolivia",
  },
  {
    value: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
    label: "Bosnia and Herzegovina",
  },
  {
    value: "Botswana",
    dial_code: "+267",
    code: "BW",
    label: "Botswana",
  },
  {
    value: "Brazil",
    dial_code: "+55",
    code: "BR",
    label: "Brazil",
  },
  {
    value: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
    label: "British Indian Ocean Territory",
  },
  {
    value: "Brunei Darussalam",
    dial_code: "+673",
    code: "BN",
    label: "Brunei Darussalam",
  },
  {
    value: "Bulgaria",
    dial_code: "+359",
    code: "BG",
    label: "Bulgaria",
  },
  {
    value: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
    label: "Burkina Faso",
  },
  {
    value: "Burundi",
    dial_code: "+257",
    code: "BI",
    label: "Burundi",
  },
  {
    value: "Cambodia",
    dial_code: "+855",
    code: "KH",
    label: "Cambodia",
  },
  {
    value: "Cameroon",
    dial_code: "+237",
    code: "CM",
    label: "Cameroon",
  },
  {
    value: "Canada",
    dial_code: "+1",
    code: "CA",
    label: "Canada",
  },
  {
    value: "Cape Verde",
    dial_code: "+238",
    code: "CV",
    label: "Cape Verde",
  },
  {
    value: "Cayman Islands",
    dial_code: "+ 345",
    code: "KY",
    label: "Cayman Islands",
  },
  {
    value: "Central African Republic",
    dial_code: "+236",
    code: "CF",
    label: "Central African Republic",
  },
  {
    value: "Chad",
    dial_code: "+235",
    code: "TD",
    label: "Chad",
  },
  {
    value: "Chile",
    dial_code: "+56",
    code: "CL",
    label: "Chile",
  },
  {
    value: "China",
    dial_code: "+86",
    code: "CN",
    label: "China",
  },
  {
    value: "Christmas Island",
    dial_code: "+61",
    code: "CX",
    label: "Christmas Island",
  },
  {
    value: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
    label: "Cocos (Keeling) Islands",
  },
  {
    value: "Colombia",
    dial_code: "+57",
    code: "CO",
    label: "Colombia",
  },
  {
    value: "Comoros",
    dial_code: "+269",
    code: "KM",
    label: "Comoros",
  },
  {
    value: "Congo",
    dial_code: "+242",
    code: "CG",
    label: "Congo",
  },
  {
    value: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    code: "CD",
    label: "Congo, The Democratic Republic of the Congo",
  },
  {
    value: "Cook Islands",
    dial_code: "+682",
    code: "CK",
    label: "Cook Islands",
  },
  {
    value: "Costa Rica",
    dial_code: "+506",
    code: "CR",
    label: "Costa Rica",
  },
  {
    value: "Cote d'Ivoire",
    dial_code: "+225",
    code: "CI",
    label: "Cote d'Ivoire",
  },
  {
    value: "Croatia",
    dial_code: "+385",
    code: "HR",
    label: "Croatia",
  },
  {
    value: "Cuba",
    dial_code: "+53",
    code: "CU",
    label: "Cuba",
  },
  {
    value: "Cyprus",
    dial_code: "+357",
    code: "CY",
    label: "Cyprus",
  },
  {
    value: "Czech Republic",
    dial_code: "+420",
    code: "CZ",
    label: "Czech Republic",
  },
  {
    value: "Denmark",
    dial_code: "+45",
    code: "DK",
    label: "Denmark",
  },
  {
    value: "Djibouti",
    dial_code: "+253",
    code: "DJ",
    label: "Djibouti",
  },
  {
    value: "Dominica",
    dial_code: "+1767",
    code: "DM",
    label: "Dominica",
  },
  {
    value: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
    label: "Dominican Republic",
  },
  {
    value: "Ecuador",
    dial_code: "+593",
    code: "EC",
    label: "Ecuador",
  },
  {
    value: "Egypt",
    dial_code: "+20",
    code: "EG",
    label: "Egypt",
  },
  {
    value: "El Salvador",
    dial_code: "+503",
    code: "SV",
    label: "El Salvador",
  },
  {
    value: "Equatorial Guinea",
    dial_code: "+240",
    code: "GQ",
    label: "Equatorial Guinea",
  },
  {
    value: "Eritrea",
    dial_code: "+291",
    code: "ER",
    label: "Eritrea",
  },
  {
    value: "Estonia",
    dial_code: "+372",
    code: "EE",
    label: "Estonia",
  },
  {
    value: "Ethiopia",
    dial_code: "+251",
    code: "ET",
    label: "Ethiopia",
  },
  {
    value: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
    label: "Falkland Islands (Malvinas)",
  },
  {
    value: "Faroe Islands",
    dial_code: "+298",
    code: "FO",
    label: "Faroe Islands",
  },
  {
    value: "Fiji",
    dial_code: "+679",
    code: "FJ",
    label: "Fiji",
  },
  {
    value: "Finland",
    dial_code: "+358",
    code: "FI",
    label: "Finland",
  },
  {
    value: "France",
    dial_code: "+33",
    code: "FR",
    label: "France",
  },
  {
    value: "French Guiana",
    dial_code: "+594",
    code: "GF",
    label: "French Guiana",
  },
  {
    value: "French Polynesia",
    dial_code: "+689",
    code: "PF",
    label: "French Polynesia",
  },
  {
    value: "Gabon",
    dial_code: "+241",
    code: "GA",
    label: "Gabon",
  },
  {
    value: "Gambia",
    dial_code: "+220",
    code: "GM",
    label: "Gambia",
  },
  {
    value: "Georgia",
    dial_code: "+995",
    code: "GE",
    label: "Georgia",
  },
  {
    value: "Georgia",
    dial_code: "+49",
    code: "DE",
    label: "Georgia",
  },
  {
    value: "Ghana",
    dial_code: "+233",
    code: "GH",
    label: "Ghana",
  },
  {
    value: "Gibraltar",
    dial_code: "+350",
    code: "GI",
    label: "Gibraltar",
  },
  {
    value: "Greece",
    dial_code: "+30",
    code: "GR",
    label: "Greece",
  },
  {
    value: "Greenland",
    dial_code: "+299",
    code: "GL",
    label: "Greenland",
  },
  {
    value: "Grenada",
    dial_code: "+1473",
    code: "GD",
    label: "Grenada",
  },
  {
    value: "Guadeloupe",
    dial_code: "+590",
    code: "GP",
    label: "Guadeloupe",
  },
  {
    value: "Guam",
    dial_code: "+1671",
    code: "GU",
    label: "Guam",
  },
  {
    value: "Guatemala",
    dial_code: "+502",
    code: "GT",
    label: "Guatemala",
  },
  {
    value: "Guernsey",
    dial_code: "+44",
    code: "GG",
    label: "Guernsey",
  },
  {
    value: "Guinea",
    dial_code: "+224",
    code: "GN",
    label: "Guinea",
  },
  {
    value: "Guinea-Bissau",
    dial_code: "+245",
    code: "GW",
    label: "Guinea-Bissau",
  },
  {
    value: "Guyana",
    dial_code: "+595",
    code: "GY",
    label: "Guyana",
  },
  {
    value: "Haiti",
    dial_code: "+509",
    code: "HT",
    label: "Haiti",
  },
  {
    value: "Holy See (Vatican City State)",
    dial_code: "+379",
    code: "VA",
    label: "Holy See (Vatican City State)",
  },
  {
    value: "Honduras",
    dial_code: "+504",
    code: "HN",
    label: "Honduras",
  },
  {
    value: "Hong Kong",
    dial_code: "+852",
    code: "HK",
    label: "Hong Kong",
  },
  {
    value: "Hungary",
    dial_code: "+36",
    code: "HU",
    label: "Hungary",
  },
  {
    value: "Iceland",
    dial_code: "+354",
    code: "IS",
    label: "Iceland",
  },
  {
    value: "India",
    dial_code: "+91",
    code: "IN",
    label: "India",
  },
  {
    value: "Indonesia",
    dial_code: "+62",
    code: "ID",
    label: "Indonesia",
  },
  {
    value: "Iran",
    dial_code: "+98",
    code: "IR",
    label: "Iran",
  },
  {
    value: "Iraq",
    dial_code: "+964",
    code: "IQ",
    label: "Iraq",
  },
  {
    value: "Ireland",
    dial_code: "+353",
    code: "IE",
    label: "Ireland",
  },
  {
    value: "Isle of Man",
    dial_code: "+44",
    code: "IM",
    label: "Isle of Man",
  },
  {
    value: "Israel",
    dial_code: "+972",
    code: "IL",
    label: "Israel",
  },
  {
    value: "Italy",
    dial_code: "+39",
    code: "IT",
    label: "Italy",
  },
  {
    value: "Jamaica",
    dial_code: "+1876",
    code: "JM",
    label: "Jamaica",
  },
  {
    value: "Japan",
    dial_code: "+81",
    code: "JP",
    label: "Japan",
  },
  {
    value: "Jersey",
    dial_code: "+44",
    code: "JE",
    label: "Jersey",
  },
  {
    value: "Jordan",
    dial_code: "+962",
    code: "JO",
    label: "Jordan",
  },
  {
    value: "Kazakhstan",
    dial_code: "+77",
    code: "KZ",
    label: "Kazakhstan",
  },
  {
    value: "Kenya",
    dial_code: "+254",
    code: "KE",
    label: "Kenya",
  },
  {
    value: "Kiribati",
    dial_code: "+686",
    code: "KI",
    label: "Kiribati",
  },
  {
    value: "North Korea",
    dial_code: "+850",
    code: "KP",
    label: "North Korea",
  },
  {
    value: "South Korea",
    dial_code: "+82",
    code: "KR",
    label: "South Korea",
  },
  {
    value: "Kuwait",
    dial_code: "+965",
    code: "KW",
    label: "Kuwait",
  },
  {
    value: "Kyrgyzstan",
    dial_code: "+996",
    code: "KG",
    label: "Kyrgyzstan",
  },
  {
    value: "Laos",
    dial_code: "+856",
    code: "LA",
    label: "Laos",
  },
  {
    value: "Latvia",
    dial_code: "+371",
    code: "LV",
    label: "Latvia",
  },
  {
    value: "Lebanon",
    dial_code: "+961",
    code: "LB",
    label: "Lebanon",
  },
  {
    value: "Lesotho",
    dial_code: "+266",
    code: "LS",
    label: "Lesotho",
  },
  {
    value: "Liberia",
    dial_code: "+231",
    code: "LR",
    label: "Liberia",
  },
  {
    value: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    code: "LY",
    label: "Libyan Arab Jamahiriya",
  },
  {
    value: "Liechtenstein",
    dial_code: "+423",
    code: "LI",
    label: "Liechtenstein",
  },
  {
    value: "Lithuania",
    dial_code: "+370",
    code: "LT",
    label: "Lithuania",
  },
  {
    value: "Luxembourg",
    dial_code: "+352",
    code: "LU",
    label: "Luxembourg",
  },
  {
    value: "Macao",
    dial_code: "+853",
    code: "MO",
    label: "Macao",
  },
  {
    value: "Macedonia",
    dial_code: "+389",
    code: "MK",
    label: "Macedonia",
  },
  {
    value: "Madagascar",
    dial_code: "+261",
    code: "MG",
    label: "Madagascar",
  },
  {
    value: "Malawi",
    dial_code: "+265",
    code: "MW",
    label: "Malawi",
  },
  {
    value: "Malaysia",
    dial_code: "+60",
    code: "MY",
    label: "Malaysia",
  },
  {
    value: "Maldives",
    dial_code: "+960",
    code: "MV",
    label: "Maldives",
  },
  {
    value: "Mali",
    dial_code: "+223",
    code: "ML",
    label: "Mali",
  },
  {
    value: "Malta",
    dial_code: "+356",
    code: "MT",
    label: "Malta",
  },
  {
    value: "Marshall Islands",
    dial_code: "+692",
    code: "MH",
    label: "Marshall Islands",
  },
  {
    value: "Martinique",
    dial_code: "+596",
    code: "MQ",
    label: "Martinique",
  },
  {
    value: "Mauritania",
    dial_code: "+222",
    code: "MR",
    label: "Mauritania",
  },
  {
    value: "Mauritius",
    dial_code: "+230",
    code: "MU",
    label: "Mauritius",
  },
  {
    value: "Mayotte",
    dial_code: "+262",
    code: "YT",
    label: "Mayotte",
  },
  {
    value: "Mexico",
    dial_code: "+52",
    code: "MX",
    label: "Mexico",
  },
  {
    value: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    code: "FM",
    label: "Micronesia, Federated States of Micronesia",
  },
  {
    value: "Moldova",
    dial_code: "+373",
    code: "MD",
    label: "Moldova",
  },
  {
    value: "Monaco",
    dial_code: "+377",
    code: "MC",
    label: "Monaco",
  },
  {
    value: "Mongolia",
    dial_code: "+976",
    code: "MN",
    label: "Mongolia",
  },
  {
    value: "Montenegro",
    dial_code: "+382",
    code: "ME",
    label: "Montenegro",
  },
  {
    value: "Montserrat",
    dial_code: "+1664",
    code: "MS",
    label: "Montserrat",
  },
  {
    value: "Morocco",
    dial_code: "+212",
    code: "MA",
    label: "Morocco",
  },
  {
    value: "Mozambique",
    dial_code: "+258",
    code: "MZ",
    label: "Mozambique",
  },
  {
    value: "Myanmar",
    dial_code: "+95",
    code: "MM",
    label: "Myanmar",
  },
  {
    value: "Namibia",
    dial_code: "+264",
    code: "NA",
    label: "Namibia",
  },
  {
    value: "Nauru",
    dial_code: "+674",
    code: "NR",
    label: "Nauru",
  },
  {
    value: "Nepal",
    dial_code: "+977",
    code: "NP",
    label: "Nepal",
  },
  {
    value: "Netherlands",
    dial_code: "+31",
    code: "NL",
    label: "Netherlands",
  },
  {
    value: "Netherlands Antilles",
    dial_code: "+599",
    code: "AN",
    label: "Netherlands Antilles",
  },
  {
    value: "New Caledonia",
    dial_code: "+687",
    code: "NC",
    label: "New Caledonia",
  },
  {
    value: "New Zealand",
    dial_code: "+64",
    code: "NZ",
    label: "New Zealand",
  },
  {
    value: "Nicaragua",
    dial_code: "+505",
    code: "NI",
    label: "Nicaragua",
  },
  {
    value: "Niger",
    dial_code: "+227",
    code: "NE",
    label: "Niger",
  },
  {
    value: "Nigeria",
    dial_code: "+234",
    code: "NG",
    label: "Nigeria",
  },
  {
    value: "Niue",
    dial_code: "+683",
    code: "NU",
    label: "Niue",
  },
  {
    value: "Norfolk Island",
    dial_code: "+672",
    code: "NF",
    label: "Norfolk Island",
  },
  {
    value: "Northern Mariana Islands",
    dial_code: "+1670",
    code: "MP",
    label: "Northern Mariana Islands",
  },
  {
    value: "Norway",
    dial_code: "+47",
    code: "NO",
    label: "Norway",
  },
  {
    value: "Oman",
    dial_code: "+968",
    code: "OM",
    label: "Oman",
  },
  {
    value: "Pakistan",
    dial_code: "+92",
    code: "PK",
    label: "Pakistan",
  },
  {
    value: "Palau",
    dial_code: "+680",
    code: "PW",
    label: "Palau",
  },
  {
    value: "Palestinian Territory, Occupied",
    dial_code: "+970",
    code: "PS",
    label: "Palestinian Territory, Occupied",
  },
  {
    value: "Panama",
    dial_code: "+507",
    code: "PA",
    label: "Panama",
  },
  {
    value: "Papua New Guinea",
    dial_code: "+675",
    code: "PG",
    label: "Papua New Guinea",
  },
  {
    value: "Paraguay",
    dial_code: "+595",
    code: "PY",
    label: "Paraguay",
  },
  {
    value: "Peru",
    dial_code: "+51",
    code: "PE",
    label: "Peru",
  },
  {
    value: "Philippines",
    dial_code: "+63",
    code: "PH",
    label: "Philippines",
  },
  {
    value: "Pitcairn",
    dial_code: "+872",
    code: "PN",
    label: "Pitcairn",
  },
  {
    value: "Poland",
    dial_code: "+48",
    code: "PL",
    label: "Poland",
  },
  {
    value: "Portugal",
    dial_code: "+351",
    code: "PT",
    label: "Portugal",
  },
  {
    value: "Puerto Rico",
    dial_code: "+1939",
    code: "PR",
    label: "Puerto Rico",
  },
  {
    value: "Qatar",
    dial_code: "+974",
    code: "QA",
    label: "Qatar",
  },
  {
    value: "Romania",
    dial_code: "+40",
    code: "RO",
    label: "Romania",
  },
  {
    value: "Russia",
    dial_code: "+7",
    code: "RU",
    label: "Russia",
  },
  {
    value: "Rwanda",
    dial_code: "+250",
    code: "RW",
    label: "Rwanda",
  },
  {
    value: "Reunion",
    dial_code: "+262",
    code: "RE",
    label: "Reunion",
  },
  {
    value: "Saint Barthelemy",
    dial_code: "+590",
    code: "BL",
    label: "Saint Barthelemy",
  },
  {
    value: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    code: "SH",
    label: "Saint Helena, Ascension and Tristan Da Cunha",
  },
  {
    value: "Saint Kitts and Nevis",
    dial_code: "+1869",
    code: "KN",
    label: "Saint Kitts and Nevis",
  },
  {
    value: "Saint Lucia",
    dial_code: "+1758",
    code: "LC",
    label: "Saint Lucia",
  },
  {
    value: "Saint Martin",
    dial_code: "+590",
    code: "MF",
    label: "Saint Martin",
  },
  {
    value: "Saint Pierre and Miquelon",
    dial_code: "+508",
    code: "PM",
    label: "Saint Pierre and Miquelon",
  },
  {
    value: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    code: "VC",
    label: "Saint Vincent and the Grenadines",
  },
  {
    value: "Samoa",
    dial_code: "+685",
    code: "WS",
    label: "Samoa",
  },
  {
    value: "San Marino",
    dial_code: "+378",
    code: "SM",
    label: "San Marino",
  },
  {
    value: "Sao Tome and Principe",
    dial_code: "+239",
    code: "ST",
    label: "Sao Tome and Principe",
  },
  {
    value: "Saudi Arabia",
    dial_code: "+966",
    code: "SA",
    label: "Saudi Arabia",
  },
  {
    value: "Senegal",
    dial_code: "+221",
    code: "SN",
    label: "Senegal",
  },
  {
    value: "Serbia",
    dial_code: "+381",
    code: "RS",
    label: "Serbia",
  },
  {
    value: "Seychelles",
    dial_code: "+248",
    code: "SC",
    label: "Seychelles",
  },
  {
    value: "Sierra Leone",
    dial_code: "+232",
    code: "SL",
    label: "Sierra Leone",
  },
  {
    value: "Singapore",
    dial_code: "+65",
    code: "SG",
    label: "Singapore",
  },
  {
    value: "Slovakia",
    dial_code: "+421",
    code: "SK",
    label: "Slovakia",
  },
  {
    value: "Slovenia",
    dial_code: "+386",
    code: "SI",
    label: "Slovenia",
  },
  {
    value: "Solomon Islands",
    dial_code: "+677",
    code: "SB",
    label: "Solomon Islands",
  },
  {
    value: "Somalia",
    dial_code: "+252",
    code: "SO",
    label: "Somalia",
  },
  {
    value: "South Africa",
    dial_code: "+27",
    code: "ZA",
    label: "South Africa",
  },
  {
    value: "South Sudan",
    dial_code: "+211",
    code: "SS",
    label: "South Sudan",
  },
  {
    value: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
  },
  {
    value: "Spain",
    dial_code: "+34",
    code: "ES",
    label: "Spain",
  },
  {
    value: "Sri Lanka",
    dial_code: "+94",
    code: "LK",
    label: "Sri Lanka",
  },
  {
    value: "Sudan",
    dial_code: "+249",
    code: "SD",
    label: "Sudan",
  },
  {
    value: "Suriname",
    dial_code: "+597",
    code: "SR",
    label: "Suriname",
  },
  {
    value: "Svalbard",
    dial_code: "+47",
    code: "SJ",
    label: "Svalbard",
  },
  {
    value: "Swaziland",
    dial_code: "+268",
    code: "SZ",
    label: "Swaziland",
  },
  {
    value: "Sweden",
    dial_code: "+46",
    code: "SE",
    label: "Sweden",
  },
  {
    value: "Switzerland",
    dial_code: "+41",
    code: "CH",
    label: "Switzerland",
  },
  {
    value: "Syrian Arab Republic",
    dial_code: "+963",
    code: "SY",
    label: "Syrian Arab Republic",
  },
  {
    value: "Taiwan",
    dial_code: "+886",
    code: "TW",
    label: "Taiwan",
  },
  {
    value: "Tajikistan",
    dial_code: "+992",
    code: "TJ",
    label: "Tajikistan",
  },
  {
    value: "Tanzania",
    dial_code: "+255",
    code: "TZ",
    label: "Tanzania",
  },
  {
    value: "Thailand",
    dial_code: "+66",
    code: "TH",
    label: "Thailand",
  },
  {
    value: "Timor-Leste",
    dial_code: "+670",
    code: "TL",
    label: "Timor-Leste",
  },
  {
    value: "Togo",
    dial_code: "+228",
    code: "TG",
    label: "Togo",
  },
  {
    value: "Tokelau",
    dial_code: "+690",
    code: "TK",
    label: "Tokelau",
  },
  {
    value: "Tonga",
    dial_code: "+676",
    code: "TO",
    label: "Tonga",
  },
  {
    value: "Trinidad and Tobago",
    dial_code: "+1868",
    code: "TT",
    label: "Trinidad and Tobago",
  },
  {
    value: "Tunisia",
    dial_code: "+216",
    code: "TN",
    label: "Tunisia",
  },
  {
    value: "Turkey",
    dial_code: "+90",
    code: "TR",
    label: "Turkey",
  },
  {
    value: "Turkmenistan",
    dial_code: "+993",
    code: "TM",
    label: "Turkmenistan",
  },
  {
    value: "Turks and Caicos Islands",
    dial_code: "+1649",
    code: "TC",
    label: "Turks and Caicos Islands",
  },
  {
    value: "Tuvalu",
    dial_code: "+688",
    code: "TV",
    label: "Tuvalu",
  },
  {
    value: "Uganda",
    dial_code: "+256",
    code: "UG",
    label: "Uganda",
  },
  {
    value: "Ukraine",
    dial_code: "+380",
    code: "UA",
    label: "Ukraine",
  },
  {
    value: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
    label: "United Arab Emirates",
  },
  {
    value: "United Kingdom",
    dial_code: "+44",
    code: "GB",
    label: "United Kingdom",
  },
  {
    value: "United States",
    dial_code: "+1",
    code: "US",
    label: "United States",
  },
  {
    value: "Uruguay",
    dial_code: "+598",
    code: "UY",
    label: "Uruguay",
  },
  {
    value: "Uzbekistan",
    dial_code: "+998",
    code: "UZ",
    label: "Uzbekistan",
  },
  {
    value: "Vanuatu",
    dial_code: "+678",
    code: "VU",
    label: "Vanuatu",
  },
  {
    value: "Venezuela",
    dial_code: "+58",
    code: "VE",
    label: "Venezuela",
  },
  {
    value: "Vietnam",
    dial_code: "+84",
    code: "VN",
    label: "Vietnam",
  },
  {
    value: "Virgin Islands, British",
    dial_code: "+1284",
    code: "VG",
    label: "Virgin Islands, British",
  },
  {
    value: "Virgin Islands, U.S.",
    dial_code: "+1340",
    code: "VI",
    label: "Virgin Islands, U.S.",
  },
  {
    value: "Wallis and Futuna",
    dial_code: "+681",
    code: "WF",
    label: "Wallis and Futuna",
  },
  {
    value: "Yemen",
    dial_code: "+967",
    code: "YE",
    label: "Yemen",
  },
  {
    value: "Zambia",
    dial_code: "+260",
    code: "ZM",
    label: "Zambia",
  },
  {
    value: "Zimbabwe",
    dial_code: "+263",
    code: "ZW",
    label: "Zimbabwe",
  },
];
